env {
    parallelism = 1
    job.mode = "BATCH"
}

source {
    LocalFile {
        path = "/home/abhi/seatunnel-demo/sales.csv"
        file_format_type = "csv"
        csv_use_header_line = true

        schema {
            fields {
                id = int
                customer = string
                product = string
                quantity = int
                price = double
            }
        }
    }
}

sink {
    Jdbc {
        url = "jdbc:postgresql://localhost:5432/seatunnel_demo"
        driver = "org.postgresql.Driver"
        username = "postgres"
        password = "postgres"
        query = "INSERT INTO sales (id, customer, product, quantity, price) VALUES (?, ?, ?, ?, ?)"
    }
}