env {
    parallelism = 1
    job.mode = "BATCH"
}

source {
    HdfsFile {
        path = "/seatunnel-demo/sales"
        file_format_type = "csv"
        field_delimiter = ","
        fs.defaultFS = "hdfs://localhost:9000"

        schema {
            fields {
                id = int
                customer = string
                product = string
                quantity = int
                price = double
            }
        }
    }
}

sink {
    Jdbc {
        url = "jdbc:postgresql://localhost:5432/seatunnel_demo"
        driver = "org.postgresql.Driver"
        username = "postgres"
        password = "postgres"
        query = "INSERT INTO sales (id, customer, product, quantity, price) VALUES (?, ?, ?, ?, ?)"
    }
}